services:
  resty-app:
    build: .
    container_name: resty-app
    depends_on:
      - redis
    ports:
      - "8080:8080"
    labels:
      - monitor=true

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: ["redis-server", "--appendonly", "yes"]

  redis-cluster:
    image: grokzen/redis-cluster:7.0.11
    container_name: redis-cluster
    environment:
      - IP=0.0.0.0
      - REDIS_CLUSTER_IP=redis-cluster
      - REDIS_CLUSTER_PORT=7000
      - REDIS_CLUSTER_REPLICAS=1
      - REDIS_CLUSTER_NODES=6
      - REDIS_CLUSTER_ANNOUNCE_IP=127.0.0.1
      - STANDALONE=false
      - CLUSTER_ONLY=true
    ports:
      - "7000-7005:7000-7005"
    volumes:
      - redis-cluster-data:/redis-data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7000"]
      interval: 10s
      timeout: 5s
      retries: 5

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
      - "8081:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro

volumes:
  redis-data:
  redis-cluster-data:
